---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repo-security-scanner
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: repo-security-scanner
    spec:
      containers:
      - name: repo-security-scanner
        image: quay.io/ukhomeofficedigital/repo-security-scanner:{{.DRONE_COMMIT_SHA}}
        ports:
          - name: http
            containerPort: 8080
        env:
          - name: GITHUB_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: GITHUB_PRIVATEKEY
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
