---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repo-security-scanner
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: repo-security-scanner
    spec:
      containers:
      - name: repo-security-scanner-webserver
        image: quay.io/ukhomeofficedigital/repo-security-scanner-webserver:{{.DRONE_COMMIT_SHA}}
        ports:
          - name: http
            containerPort: 8080
        # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        env:
          - name: GITHUB_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                name: repo-security-scanner
                key: GITHUB_PRIVATEKEY
          - name: GITHUB_WEBHOOKSECRET
            valueFrom:
              secretKeyRef:
                name: repo-security-scanner
                key: GITHUB_WEBHOOKSECRET

      - name: repo-security-scanner-elasticsearch
        image: elasticsearch:5
        ports:
          - name: elasticsearch
            containerPort: 9200
            livenessProbe:
              httpGet:
                path: /healthz
                port: http
            readinessProbe:
              httpGet:
                path: /healthz
                port: http

      - name: repo-security-scanner-elastalert
        image: quay.io/ukhomeofficedigital/repo-security-scanner-elastalert:{{.DRONE_COMMIT_SHA}}
        env:
          - name: ELASTICSEARCH_URL
          - name: NOTIFICATION_EMAILS
            valueFrom:
              secretKeyRef:
                name: repo-security-scanner
                key: NOTIFICATION_EMAILS
          - name: GOVUK_NOTIFY_TEMPLATE_ID
            valueFrom:
              secretKeyRef:
                name: repo-security-scanner
                key: GOVUK_NOTIFY_TEMPLATE_ID
          - name: GOVUK_NOTIFY_API_KEY
            valueFrom:
              secretKeyRef:
                name: repo-security-scanner
                key: GOVUK_NOTIFY_API_KEY
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
